### ISSUE TITLE
Which version of the Adafruit_TinyUSB library is being used with Multi?

### ISSUE THREAD

**Issue by m-r-m-s** [pangrus/multi#1]
Hi @pangrus , I am a big fan of this project and hope to build some day! I am just getting started with the XIAO and when I was trying the basic [MIDI example](https://wiki.seeedstudio.com/Wio-Terminal-USBCLIENT-MIDI/) on Seeed Studio's website, I ran into the same problem that is described here: [https://forums.adafruit.com/viewtopic.php?f=25&t=179789](https://forums.adafruit.com/viewtopic.php?f=25&t=179789)

I then tried to compile the multi [MIDI converter code](https://github.com/pangrus/multi/tree/main/multi_software/midi_converter) and ran into the same issue. When I downgraded to the 0.10.5 version of Adafruit_TinyUSB library both sketches work with no issue.

It may be helpful to include this caveat in the ReadMe file here. Thanks!

**Comment by pangrus** [comment]
I totally agree. I'm going to edit the readme. Thank you!

**Comment by m-r-m-s** [comment]
> I totally agree. I'm going to edit the readme. Thank you!

Great! And thank you for all your work on Multi =)
